name: genai blog post generator
on:
    workflow_dispatch:
    schedule:
        - cron: "0 9 * * *"
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            actions: read
            contents: write
            pull-requests: write
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: "recursive"
                  fetch-depth: 10
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: yarn
            - run: yarn install --frozen-lockfile
            - name: compile
              run: yarn compile
            - name: generate blog post
              run: yarn genai:blog-post --out-trace $GITHUB_STEP_SUMMARY
              env:
                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                  OPENAI_API_TYPE: ${{ secrets.OPENAI_API_TYPE }}
                  OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
            - name: docs
              run: yarn build:docs
            - uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  file_pattern: "docs/src/content/docs/blog/drafts/*.md"
                  commit_message: "[genai] generated blog posts"
                  commit_user_name: "genaiscript"
